### PR TITLE
Remove unused code branch In GitCredentialsProviderFactory

### LINKED ISSUE #2674: Possible unused branch in GitCredentialsProviderFactory
**Describe the bug**
It seems the branch starting on line 99 is never executed because whenever `hasText(username)` is true, the branch starting on line 93 is executed.

https://github.com/spring-cloud/spring-cloud-config/blob/e7a69671b3a9242e2412e030e8660af4a194f56c/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/GitCredentialsProviderFactory.java#L93-L106

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Fixes #2674

### CODE REVIEW

File: spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/GitCredentialsProviderFactory.java [hunk 1]
```diff
@@ -92,13 +92,6 @@ else if (hasText(username)) {
 			this.logger.debug("Constructing UsernamePasswordCredentialsProvider for URI " + uri);
 			provider = new UsernamePasswordCredentialsProvider(username, password.toCharArray());
 		}
-		else if (hasText(username) && !hasText(passphrase)) {
```
Comment (spencergibb) [inline spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/GitCredentialsProviderFactory.java:95]: Maybe it shouldn't be removed and add `&& hasText(password)` to the branch above? That will fix a potential NPE there anyway.

Comment (ryanjbaxter) [reply spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/GitCredentialsProviderFactory.java:95]: @spencergibb This logic is tasting if _passphrase_ has text not password.  I agree that we should add a null check for `password` above.  But we probably don't want to use a `hasText` check since having an empty string for password is valid (we have a test for that).

Comment (spencergibb) [reply spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/GitCredentialsProviderFactory.java:95]: right, null check works

**Review by spencergibb — APPROVED** [review]
