### PR TITLE
Do not combine profiles when spring.cloud.config.pofiles is set.

### LINKED ISSUE #2349: Version 4.0.4, unable to connect to Cloud Config if we have cloud config profile and spring environment profile.
Description:

We have a profile property to connect to appconfig.(spring.cloud.config.profile)
with spring-cloud-config-client-4.0.4.jar, in class ConfigServicePropertySourceLocator, there is  a new method which combines profile from property and environment with comma separated.
So, finally profile value while connecting to appconfig will be like below and failing app-config call.

HTTP GET https://XXXXXXXXXX/appconfig/properties/<ModuleID>/<PROFILE-XYX,ABC>/<LABEL>
This is failing.

Even though profile properties are overrider at line 122 ConfigClientProperties properties = this.defaultProperties.override(environment);

in the next line, profile value is getting updated by appending with all the profiles
properties.setProfile(String.join(",", combineProfiles(properties, environment)));

So in method getRemoteEnvironment, while preparing the URL, profile path param is goign as comma separated and there by causing issue.

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Fixes #2349

### CODE REVIEW

File: spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java [hunk 1]
```diff
@@ -92,6 +92,9 @@ private List<String> combineProfiles(ConfigClientProperties properties,
 		if (!ObjectUtils.isEmpty(properties.getProfile())) {
 			combinedProfiles = Stream.of(properties.getProfile().split(",")).map(String::trim).filter(s -> !s.isEmpty())
 					.collect(Collectors.toList());
+			// If spring.cloud.config.profiles is set it should override all other
+			// profiles set other ways
+			return combinedProfiles;
```
Comment (spencergibb) [inline spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java:97]: This makes this method weird right? It's no longer combining profiles. It's returning either the config props profiles, or the active profiles, or default profiles

**Comment by spencergibb** [comment]
Nothing else broke with the build, so maybe it is ok, but the terminology of the method and some variables don't make sense anymore.

**Comment by ryanjbaxter** [comment]
@spencergibb let me know if this makes things clearer

**Review by spencergibb — APPROVED** [review]
