### PR TITLE
Cannot configure endpoint for AWS Secrets Manager or Parameter Store

### LINKED ISSUE #2025: Cannot configure endpoint for AWS Secrets Manager or Parameter Store
**Describe the bug**
Cannot configure endpoint for AWS Secrets Manager or Parameter Store integration.  The application fails to start with the following exception

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsSecretsManagerEnvironmentRepository' defined in class path resource [org/springframework/cloud/config/server/config/AwsSecretsManagerRepositoryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.config.server.environment.AwsSecretsManagerEnvironmentRepository]: Factory method 'awsSecretsManagerEnvironmentRepository' threw exception; nested exception is java.lang.IllegalStateException: Only one of Region or EndpointConfiguration may be set.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.cloud.config.server.ConfigServerApplication.main(ConfigServerApplication.java:35) ~[spring-cloud-config-server-3.1.0.jar:3.1.0]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.config.server.environment.AwsSecretsManagerEnvironmentRepository]: Factory method 'awsSecretsManagerEnvironmentRepository' threw exception; nested exception is java.lang.IllegalStateException: Only one of Region or EndpointConfiguration may be set.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.13.jar:5.3.13]
	... 18 common frames omitted
Caused by: java.lang.IllegalStateException: Only one of Region or EndpointConfiguration may be set.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:450) ~[aws-java-sdk-core-1.11.935.jar:na]
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424) ~[aws-java-sdk-core-1.11.935.jar:na]
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46) ~[aws-java-sdk-core-1.11.935.jar:na]
	at org.springframework.cloud.config.server.environment.AwsSecretsManagerEnvironmentRepositoryFactory.build(AwsSecretsManagerEnvironmentRepositoryFactory.java:56) ~[spring-cloud-config-server-3.1.0.jar:3.1.0]
	at org.springframework.cloud.config.server.config.AwsSecretsManagerRepositoryConfiguration.awsSecretsManagerEnvironmentRepository(EnvironmentRepositoryConfiguration.java:438) ~[spring-cloud-config-server-3.1.0.jar:3.1.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.13.jar:5.3.13]
	... 19 common frames omitted

```

The problem is `org.springframework.cloud.config.server.environment.AwsSecretsManagerEnvironmentRepositoryFactory` and `org.springframework.cloud.config.server.environment.AwsParameterStoreEnvironmentRepositoryFactory` do not configure the region in the AwsClientBuilder.EndpointConfiguration, as is done in `org.springframework.cloud.config.server.environment.AwsS3EnvironmentRepositoryFactory`

I have submitted PR #2023 to fix it

**Sample**
```yaml
spring:
  profiles:
    active: awssecretsmanager
  cloud:
    config:
      server:
        aws-secretsmanager:
          endpoint: localhost.localstack.cloud:4566
          region: us-east-1

```

```yaml
spring:
  profiles:
    active: awsparamstore
  cloud:
    config:
      server:
        awsparamstore:
          endpoint: localhost.localstack.cloud:4566
          region: us-east-1

```

### PR DESCRIPTION
**Pull request by hyness**
Fixes #2025

### CODE REVIEW

File: spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractAwsClientBuilderConfigurer.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+ * limitations under the License.
+ */
+
+package org.springframework.cloud.config.server.environment;
+
+import com.amazonaws.client.builder.AwsClientBuilder;
+import com.amazonaws.client.builder.AwsSyncClientBuilder;
+
+abstract class AbstractAwsClientBuilderConfigurer {
+	void configureClientBuilder(AwsSyncClientBuilder<?, ?> clientBuilder, String region, String endpoint) {
```
Comment (spencergibb) [inline spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractAwsClientBuilderConfigurer.java:23]: Please make this method static rather than having to inherit from the class.

**Review by spencergibb — CHANGES_REQUESTED** [review]

File: spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractAwsClientBuilderConfigurer.java (hunk 1 above)
Comment (hyness) [reply spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractAwsClientBuilderConfigurer.java]: Done

File: spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsClientBuilderConfigurer.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+import com.amazonaws.client.builder.AwsClientBuilder;
+import com.amazonaws.client.builder.AwsSyncClientBuilder;
+
+abstract class AwsClientBuilderConfigurer {
+	private AwsClientBuilderConfigurer() {
+	}
+
+	static void configureClientBuilder(AwsSyncClientBuilder<?, ?> clientBuilder, String region, String endpoint) {
+		if (region != null) {
```
Comment (ryanjbaxter) [inline spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsClientBuilderConfigurer.java:27]: Instead of checking for `null` can you use `StringUtils`?

**Review by ryanjbaxter — CHANGES_REQUESTED** [review]
Can you submit this against the 3.0.x branch and we can then merge it forward?

File: spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsClientBuilderConfigurer.java (hunk 2 above)
Comment (hyness) [reply spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsClientBuilderConfigurer.java]: Done

**Comment by hyness** [comment]
> Can you submit this against the 3.0.x branch and we can then merge it forward?



> Can you submit this against the 3.0.x branch and we can then merge it forward?

Do you mean the 3.1.x branch?  I don't see the code in the 3.0.x branch.  According to [these release notes](https://spring.io/blog/2021/12/02/spring-cloud-2021-0-0-codename-jubilee-has-been-released) the AWS Secrets Manager and Paraameter Store integration are 3.1.x features

**Comment by spencergibb** [comment]
Yes. New features in 3.1.x
