### PR TITLE
Use ConfigClientProperties if it exists in the BootstrapContext

### LINKED ISSUE #1919: /refresh (or /busrefresh) lose configserver uri (discovery first bootstrap)
SpringBoot 2.7
SpringCloud 2020.0.3

**Describe the bug**
Application use config server client with discovery first bootstrap (Eureka). 
When sending a request on /actuator/refresh, the url of configserver is lost

**Sample**
https://github.com/guerricm/config-server-pbrefresh

start eureka on port 8761
start configserver on port 9999
start service A : configserver use the good url
call http://localhost:8080/actuator/refresh
configserver client use the default localhost:8888 url

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.7)

2021-06-23 18:46:55.061  INFO 21780 --- [           main] o.s.b.context.config.ConfigDataLoader    : Fetching config from server at : http://pc-11455.huge.ad.hcuge.ch:9999/
2021-06-23 18:46:55.063  WARN 21780 --- [           main] o.s.b.context.config.ConfigDataLoader    : Could not locate PropertySource ([ConfigServerConfigDataResource@2687f956 uris = array<String>['http://pc-11455.huge.ad.hcuge.ch:9999/'], optional = true, profiles = list['default']]): None of labels [] found
2021-06-23 18:47:02.958  INFO 21780 --- [oundedElastic-1] o.s.b.context.config.ConfigDataLoader    : Fetching config from server at : http://localhost:8888
2021-06-23 18:47:03.961  INFO 21780 --- [oundedElastic-1] o.s.b.context.config.ConfigDataLoader    : Connect Timeout Exception on Url - http://localhost:8888. Will be trying the next url if available
2021-06-23 18:47:03.963  WARN 21780 --- [oundedElastic-1] o.s.b.context.config.ConfigDataLoader    : Could not locate PropertySource ([ConfigServerConfigDataResource@82da5ef uris = array<String>['http://localhost:8888'], optional = true, profiles = list['default']]): I/O error on GET request for "http://localhost:8888/service-a/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect

```

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Fixes  #1919

### CODE REVIEW

File: spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolverTests.java [hunk 1]
```diff
@@ -139,10 +142,35 @@ void uriWithParamsParsesProperties() {
 	}
 
 	@Test
-	void urisInLocationOverridesProperty() {
```
Comment (spencergibb) [inline spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolverTests.java:142]: I think this test is still good to have

File: spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolverTests.java [hunk 2]
```diff
@@ -139,10 +142,35 @@ void uriWithParamsParsesProperties() {
...
+		ConfigClientProperties configClientProperties = new ConfigClientProperties();
+		configClientProperties.setUri(new String[] { "http://myuri" });
+		when(bootstrapContext.get(eq(ConfigClientProperties.class))).thenReturn(configClientProperties);
+		when(context.getBootstrapContext()).thenReturn(bootstrapContext);
+		List<ConfigServerConfigDataResource> resources = this.resolver.resolveProfileSpecific(context,
+				ConfigDataLocation.of("configserver:http://locationuri"), mock(Profiles.class));
+		assertThat(resources).hasSize(1);
+		verify(bootstrapContext, times(1)).get(eq(ConfigClientProperties.class));
+		ConfigServerConfigDataResource resource = resources.get(0);
+		assertThat(resource.getProperties().getUri()).isEqualTo(new String[] { "http://locationuri" });
```
Comment (spencergibb) [inline spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolverTests.java:157]: Should there be a test that is just `configserver:` that gets the uri from the existing properties?

File: spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolverTests.java (hunk 1 above)
Comment (ryanjbaxter) [reply spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolverTests.java:142]: 🤦‍♂️ I didnt mean to remove that!

**Review by spencergibb — APPROVED** [review]
